import type { Language } from '@/contexts/LanguageContext';

/**
 * Product content is seeded in Romanian because that is the source language of
 * the catalogue. Keep the catalogue data language-neutral and translate it at
 * the presentation boundary instead of leaking Romanian copy into the English
 * storefront.
 */
const featureTranslations: Record<string, string> = {
  'Note de vârf: Trandafir de Damasc, Iasomie': 'Top notes: Damask rose, jasmine',
  'Note de mijloc: Iris, Ylang-Ylang': 'Middle notes: iris, ylang-ylang',
  'Note de bază: Mosc, Ambră, Vanilie': 'Base notes: musk, amber, vanilla',
  'Concentrație: Parfum (25%)': 'Concentration: Parfum (25%)',
  'Persistență îndelungată: 8-10 ore': 'Long-lasting: 8–10 hours',
  'Fabricat în Franța': 'Made in France',
  'Ingrediente de cea mai înaltă calitate': 'Highest-quality ingredients',
  'Note de vârf: bergamotă, cardamom': 'Top notes: bergamot, cardamom',
  'Note de mijloc: trandafir, iasomie': 'Middle notes: rose, jasmine',
  'Note de bază: mosc, ambră, vanilie': 'Base notes: musk, amber, vanilla',
  'Concentrație: Eau de Parfum': 'Concentration: Eau de Parfum',
  'Persistență: 8-10 ore': 'Longevity: 8–10 hours',
  'Ambalaj de lux': 'Luxury packaging',
  'Note de vârf: lămâie, lime, grapefruit': 'Top notes: lemon, lime, grapefruit',
  'Note de mijloc: mentă, busuioc': 'Middle notes: mint, basil',
  'Note de bază: lemn de cedru, mosc': 'Base notes: cedarwood, musk',
  'Concentrație: Eau de Toilette': 'Concentration: Eau de Toilette',
  'Persistență: 4-6 ore': 'Longevity: 4–6 hours',
  'Potrivit pentru utilizare zilnică': 'Suitable for everyday wear',
  'Ambalaj eco-friendly': 'Eco-friendly packaging',
  'Note de vârf: bergamotă, piper negru': 'Top notes: bergamot, black pepper',
  'Note de mijloc: cedru, santal': 'Middle notes: cedarwood, sandalwood',
  'Note de bază: vetiver, patchouli, ambră': 'Base notes: vetiver, patchouli, amber',
  'Persistență: 7-9 ore': 'Longevity: 7–9 hours',
  'Fabricat cu ingrediente rare': 'Made with rare ingredients',
  'Sticlă elegantă din sticlă groasă': 'Elegant thick-glass bottle',
  'Note de vârf: citrice, mentă': 'Top notes: citrus, mint',
  'Note de mijloc: note marine, lavandă': 'Middle notes: marine notes, lavender',
  'Note de bază: musc, ambră': 'Base notes: musk, amber',
  'Persistență: 5-7 ore': 'Longevity: 5–7 hours',
  'Inspirat de coastele mediteraneene': 'Inspired by the Mediterranean coast',
  'Ambalaj premium': 'Premium packaging',
  'Note de vârf: piper negru, nucșoară': 'Top notes: black pepper, nutmeg',
  'Note de mijloc: scorțișoară, cuișoare': 'Middle notes: cinnamon, clove',
  'Note de bază: vanilie, lemn de oud, tabac': 'Base notes: vanilla, oud, tobacco',
  'Concentrație: Extrait de Parfum': 'Concentration: Extrait de Parfum',
  'Persistență: 10-12 ore': 'Longevity: 10–12 hours',
  'Fabricat cu ingrediente rare și prețioase': 'Made with rare and precious ingredients',
  'Sticlă de lux cu capac auriu': 'Luxury bottle with a gold cap',
  'Hidratare intensă de lungă durată': 'Long-lasting intensive hydration',
  'Formula îmbogățită cu acid hialuronic': 'Formula enriched with hyaluronic acid',
  'Conține ceramide pentru refacerea barierei pielii': 'Contains ceramides to restore the skin barrier',
  'Ulei de argan pentru nutriție': 'Argan oil for nourishment',
  'Fără parabeni și sulfați': 'Free from parabens and sulfates',
  'Potrivită pentru ten uscat și deshidratat': 'Suitable for dry and dehydrated skin',
  'Testată dermatologic': 'Dermatologically tested',
  'Reduce ridurile fine și liniile de expresie': 'Reduces fine lines and expression lines',
  'Diminuează cearcănele și pungile de sub ochi': 'Reduces dark circles and under-eye puffiness',
  'Conține peptide pentru stimularea colagenului': 'Contains peptides to support collagen production',
  'Cafeină pentru reducerea pungilor și a cearcănelor': 'Caffeine to reduce puffiness and dark circles',
  'Extract de ceai verde cu proprietăți antioxidante': 'Green tea extract with antioxidant properties',
  'Textura ușoară, non-grasă': 'Light, non-greasy texture',
  'Oftalmologic testată': 'Ophthalmologically tested',
  'Hidratare intensă și de lungă durată': 'Intensive, long-lasting hydration',
  'Unt de shea pentru repararea pielii uscate': 'Shea butter to repair dry skin',
  'Ulei de măsline pentru nutriție': 'Olive oil for nourishment',
  'Vitamina E cu proprietăți antioxidante': 'Vitamin E with antioxidant properties',
  'Parfum delicat și relaxant': 'Delicate, relaxing fragrance',
  'Formulă non-grasă, cu absorbție rapidă': 'Non-greasy, fast-absorbing formula',
  'Protejează împotriva factorilor externi': 'Protects against external factors',
  'Hidratare intensă pentru 48 de ore': '48-hour intensive hydration',
  'Unt de shea organic pentru nutriție': 'Organic shea butter for nourishment',
  'Ulei de cocos pentru catifelare': 'Coconut oil for softness',
  'Fără parabeni și siliconi': 'Free from parabens and silicones',
  'Potrivită pentru toate tipurile de piele': 'Suitable for all skin types',
  'Retinol pentru stimularea reînnoirii celulare': 'Retinol to support cell renewal',
  'Peptide pentru producția de colagen': 'Peptides to support collagen production',
  'Uleiuri naturale pentru nutriție': 'Natural oils for nourishment',
  'Ceramide pentru refacerea barierei cutanate': 'Ceramides to restore the skin barrier',
  'Textură bogată și reconfortantă': 'Rich, comforting texture',
  'Parfum relaxant pentru un somn liniștit': 'Relaxing fragrance for restful sleep',
  'Cafeină pentru stimularea microcirculației': 'Caffeine to stimulate microcirculation',
  'Extract de centella asiatica pentru fermitate': 'Centella asiatica extract for firmness',
  'Complex de iod marin pentru drenaj limfatic': 'Marine iodine complex for lymphatic drainage',
  'Reduce aspectul de coajă de portocală': 'Reduces the appearance of cellulite',
  'Îmbunătățește elasticitatea pielii': 'Improves skin elasticity',
  'Textura ușoară, cu absorbție rapidă': 'Light, fast-absorbing texture',
  'Rezultate vizibile în 4-6 săptămâni de utilizare': 'Visible results in 4–6 weeks of use',
  '15% Vitamina C stabilizată': '15% stabilized vitamin C',
  'Acid glicolic pentru exfoliere blândă': 'Glycolic acid for gentle exfoliation',
  'Extract de arbore de ceai cu proprietăți antioxidante': 'Tea tree extract with antioxidant properties',
  'Reduce aspectul petelor pigmentare': 'Reduces the appearance of dark spots',
  'Stimulează producția de colagen': 'Supports collagen production',
  'Fără parfum și alcool': 'Fragrance- and alcohol-free',
  'Argilă Kaolin pentru purificare profundă': 'Kaolin clay for deep purification',
  'Cărbune activ pentru detoxifiere': 'Activated charcoal for detoxification',
  'Extract de hamamelis cu proprietăți astringente': 'Witch hazel extract with astringent properties',
  'Curăță porii și reduce aspectul acestora': 'Cleans pores and minimizes their appearance',
  'Absoarbe excesul de sebum': 'Absorbs excess sebum',
  'Se usucă complet în 10-15 minute': 'Dries completely in 10–15 minutes',
  'Potrivită pentru utilizare săptămânală': 'Suitable for weekly use',
  'Curățare delicată și eficientă': 'Gentle, effective cleansing',
  'Îndepărtează machiajul, inclusiv cel rezistent la apă': 'Removes makeup, including waterproof formulas',
  'Acid hialuronic pentru hidratare': 'Hyaluronic acid for hydration',
  'Extract de aloe vera pentru calmare': 'Aloe vera extract to soothe',
  'pH echilibrat': 'Balanced pH',
  'Fără sulfați și parabeni': 'Free from sulfates and parabens',
  'Niacinamidă pentru reducerea porilor': 'Niacinamide to minimize pores',
  'Panthenol pentru calmare': 'Panthenol to soothe',
  'Fără alcool și parfum': 'Alcohol- and fragrance-free',
  'Potrivit pentru ten mixt și gras': 'Suitable for combination and oily skin',
  'Ulei de argan bogat în vitamina E': 'Argan oil rich in vitamin E',
  'Ulei de jojoba similar cu sebumul natural': 'Jojoba oil similar to natural sebum',
  'Ulei de trandafir sălbatic bogat în vitamina C': 'Rosehip oil rich in vitamin C',
  'Omega 3, 6 și 9 pentru regenerare': 'Omega 3, 6 and 9 for renewal',
  'Textura ușoară, non-comedogenică': 'Light, non-comedogenic texture',
  'Fără parfumuri sintetice': 'Free from synthetic fragrances',
  'Potrivit pentru ten uscat și matur': 'Suitable for dry and mature skin',
};

const copyTranslations: Record<string, { description?: string; details?: string }> = {
  'parfum-floral-extravagance': {
    description: 'Floral Extravagance is an olfactory masterpiece combining precious floral notes with subtle oriental accents. Sophisticated and elegant, it is made for special occasions or everyday moments when you want to stand out. Its lasting presence wraps you in refinement throughout the day.',
    details: 'An elegant floral fragrance with top notes of Damask rose and jasmine, followed by a heart of iris and ylang-ylang. Warm musk, amber and vanilla form a deep, lasting base.',
  },
  'parfum-oriental-mystique': {
    description: 'A sophisticated oriental fragrance with warm notes of vanilla, musk and sandalwood. Perfect for elegant evenings and special occasions.',
    details: 'Oriental Mystique is a rich, mysterious composition for moments when you want to leave an impression. Its lasting trail stays with you throughout the evening.',
  },
  'parfum-fresh-citrus': {
    description: 'An invigorating fragrance with fresh citrus notes and green accents. Perfect for daytime wear and warm summer days.',
    details: 'Fresh Citrus brings a wave of freshness to our collection. Vibrant citrus notes meet green accents for an energizing olfactory experience.',
  },
  'parfum-woody-elegance': {
    description: 'A sophisticated woody fragrance with warm notes of sandalwood, cedar and vetiver. Ideal for men who appreciate classic elegance and refinement.',
    details: 'Woody Elegance is a refined composition that projects confidence. Its woody notes bring depth and character to this distinctive fragrance.',
  },
  'parfum-aquatic-breeze': {
    description: 'A fresh aquatic fragrance that evokes sea breeze and clean coastal air. Perfect for warm summer days and lovers of marine notes.',
    details: 'Aquatic Breeze captures the essence of the sea in an elegant bottle. Fresh and invigorating, it transports you instantly to the shore.',
  },
  'parfum-spicy-noir': {
    description: 'A bold, seductive fragrance with spicy notes and rich oriental accents. Perfect for special evenings and for men who are not afraid to stand out.',
    details: 'Spicy Noir is an intense, mysterious fragrance combining spicy notes with rich oriental accents. Made for the man who leaves an unforgettable impression.',
  },
  'crema-contur-ochi-anti-age': {
    description: 'This eye contour cream effectively combats signs of ageing in the delicate eye area. It reduces wrinkles, dark circles and under-eye puffiness for a younger, rested appearance.',
    details: 'A targeted cream for the delicate eye area, formulated to address wrinkles, dark circles and puffiness. Peptides, caffeine and green tea extract support visible results.',
  },
  'crema-de-maini-silk': {
    description: 'Silk Hand Cream provides intense hydration and protection for dry, stressed hands. Its rich formula with shea butter, olive oil and vitamin E nourishes and repairs, leaving hands soft and smooth.',
    details: 'A luxurious hand cream that deeply hydrates and protects against external stressors. Its silky texture absorbs quickly without a greasy finish.',
  },
  'crema-de-corp-intense': {
    description: 'Intense Body Cream provides deep, long-lasting hydration for dry and dehydrated skin. Shea butter, coconut oil and vitamin E nourish skin, leaving it soft, supple and revitalized.',
    details: 'A luxurious cream for intense full-body hydration. Shea butter, coconut oil and vitamin E provide nourishment and protection in a rich texture that absorbs quickly.',
  },
};

export const localizeProductFeature = (feature: string, language: Language) =>
  language === 'en' ? featureTranslations[feature] || feature : feature;

export const localizeProductCopy = (
  slug: string,
  field: 'description' | 'details',
  value: string,
  language: Language,
) => language === 'en' ? copyTranslations[slug]?.[field] || value : value;
